apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: abakhar217/user-service:${BUILD_NUMBER}
          ports:
            - containerPort: 8080
          env:
            # PostgreSQL Configuration
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://user-service-db:5432/user_db"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                  secretKeyRef:
                      name: postgres-secrets
                      key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                  secretKeyRef:
                     name: postgres-secrets
                     key: POSTGRES_PASSWORD
            # Kafka Configuration
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-deployment:9092"
            - name: KAFKA_TOPIC
              value: "user-events" # You can change this based on your application topic
          # Other env vars can be set below
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
